name: Gobot
on:
  workflow_dispatch:
    inputs:
      godot-version:
        description: Godot Version
        default: '4.3'
      environment:
        description: Pages Environment
        type: environment
      delete-old-pages:
        description: Delete Old Pages
        type: boolean
permissions:
  pages: write
  id-token: write
  deployments: write
jobs:
  Gobot:
    uses: rakkarage/auto/.github/workflows/gobot.yml@main
    with:
      godot-version: ${{ github.event.inputs.godot-version }}
      environment: ${{ github.event.inputs.environment }}
      delete-old-pages: ${{ github.event.inputs.delete-old-pages }}
